// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxV67Fau8Tlwa8l5-jxmSP8aSeJHKXTTE',
    appId: '1:926802291221:web:5d4e6c46715e8ce01cfc1c',
    messagingSenderId: '926802291221',
    projectId: 'chat-app-2026-87077',
    authDomain: 'chat-app-2026-87077.firebaseapp.com',
    storageBucket: 'chat-app-2026-87077.firebasestorage.app',
    measurementId: 'G-KBH1QRLJ3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqD_4z8uTTYa8AqFhpv2bxcQJmV3HDXZw',
    appId: '1:926802291221:android:05e8c39b13a0ab0f1cfc1c',
    messagingSenderId: '926802291221',
    projectId: 'chat-app-2026-87077',
    storageBucket: 'chat-app-2026-87077.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDci0PuTO6dr5ZYMlM4P-S2JLrYk2_H8uM',
    appId: '1:926802291221:ios:6787bb971a8f0c941cfc1c',
    messagingSenderId: '926802291221',
    projectId: 'chat-app-2026-87077',
    storageBucket: 'chat-app-2026-87077.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDci0PuTO6dr5ZYMlM4P-S2JLrYk2_H8uM',
    appId: '1:926802291221:ios:6787bb971a8f0c941cfc1c',
    messagingSenderId: '926802291221',
    projectId: 'chat-app-2026-87077',
    storageBucket: 'chat-app-2026-87077.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxV67Fau8Tlwa8l5-jxmSP8aSeJHKXTTE',
    appId: '1:926802291221:web:7e2df633cdd982701cfc1c',
    messagingSenderId: '926802291221',
    projectId: 'chat-app-2026-87077',
    authDomain: 'chat-app-2026-87077.firebaseapp.com',
    storageBucket: 'chat-app-2026-87077.firebasestorage.app',
    measurementId: 'G-CD5QX4W1MV',
  );
}
